# -*- coding: utf-8 -*-
"""R prg2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0YU1VHUUi9UrzpkZMJbT7qoW5qV1Gbr
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(data.table)
# 
# n <- 500000
# dt <- data.table(
#   TransactionID = 1:n
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(data.table)
# 
# set.seed(200000)
# 
# n <- 500000
# 
# dt <- data.table(
#   TransactionID = 1:n,
#   CustomerID = sample(1000:9999, n, replace = TRUE),
#   CustomerName = paste0("Customer_", sample(1:10000, n, replace = TRUE)),
#   Gender = sample(c("Male", "Female"), n, replace = TRUE),
#   Age = sample(18:70, n, replace = TRUE),
#   ProductID = sample(100:999, n, replace = TRUE),
#   ProductName = paste0("Product_", sample(1:500, n, replace = TRUE)),
#   Category = sample(c("Electronics","Clothing","Grocery","Home","Sports"), n, replace = TRUE),
#   Quantity = sample(1:10, n, replace = TRUE),
#   UnitPrice = runif(n, 100, 5000),
#   Discount = runif(n, 0, 30),
#   GST = runif(n, 5, 18),
#   PaymentMethod = sample(c("Cash","Card","UPI","Net Banking"), n, replace = TRUE),
#   City = sample(c("Chennai","Madurai","Coimbatore","Trichy","Salem"), n, replace = TRUE),
#   State = "Tamil Nadu",
#   OrderDate = sample(seq.Date(as.Date("2023-01-01"), as.Date("2024-12-31"), by="day"), n, replace = TRUE),
#   SalesPerson = paste0("SP_", sample(1:200, n, replace = TRUE))
# )
# 
# # Save dataset
# fwrite(dt, "sales_transactions.csv")
# 
# # Display outputs
# head(dt, 10)
# tail(dt, 10)
# dim(dt)
# str(dt)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# dt <- fread("sales_transactions.csv")
# 
# head(dt)
# tail(dt)
# names(dt)
# summary(dt)
# 
# # Missing values
# colSums(is.na(dt))
# 
# # Duplicates
# sum(duplicated(dt))
# 
# # Unique counts
# uniqueN(dt$CustomerID)
# uniqueN(dt$ProductID)
# uniqueN(dt$City)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# dt <- unique(dt)
# 
# dt[, OrderDate := as.Date(OrderDate)]
# 
# setcolorder(dt, c("TransactionID","CustomerID","CustomerName","Gender","Age",
#                   "ProductID","ProductName","Category","Quantity","UnitPrice",
#                   "Discount","GST","PaymentMethod","City","State","OrderDate","SalesPerson"))
# 
# head(dt)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Filtering
# dt[City == "Chennai"]
# dt[City == "Chennai" & Quantity > 5]
# 
# # Sorting
# dt[order(UnitPrice)]
# dt[order(-UnitPrice)]
# 
# # Top 20
# dt[order(-UnitPrice)][1:20]
# dt[order(-Quantity)][1:20]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# dt[, Revenue := Quantity * UnitPrice]
# dt[, DiscountAmount := Revenue * Discount / 100]
# dt[, GSTAmount := Revenue * GST / 100]
# dt[, NetRevenue := Revenue - DiscountAmount + GSTAmount]
# 
# head(dt)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# setkey(dt, CustomerID)
# dt[.(1234)]
# 
# setkey(dt, ProductID)
# dt[.(200)]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# customer_summary <- dt[, .(
#   TotalOrders = .N,
#   TotalRevenue = sum(NetRevenue),
#   AvgRevenue = mean(NetRevenue)
# ), by = CustomerID]
# 
# head(customer_summary)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Customer Summary
# customer_summary <- dt[, .(
#   TotalOrders = .N,
#   TotalRevenue = sum(NetRevenue),
#   AvgRevenue = mean(NetRevenue)
# ), by = CustomerID]
# 
# # Product Summary
# product_summary <- dt[, .(
#   TotalQuantity = sum(Quantity),
#   TotalRevenue = sum(NetRevenue)
# ), by = ProductName]
# 
# # City Summary
# city_summary <- dt[, .(
#   Transactions = .N,
#   TotalRevenue = sum(NetRevenue)
# ), by = City]
# 
# # Category Summary
# category_summary <- dt[, .(
#   TotalRevenue = sum(NetRevenue),
#   AvgRevenue = mean(NetRevenue)
# ), by = Category]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # 1 Highest revenue city
# city_summary[order(-TotalRevenue)][1]
# 
# # 2 Product with max sales
# product_summary[order(-TotalRevenue)][1]
# 
# # 3 Customer with highest orders
# customer_summary[order(-TotalOrders)][1]
# 
# # 4 Most used payment method
# dt[, .N, by = PaymentMethod][order(-N)][1]
# 
# # 5 Average transaction value
# mean(dt$NetRevenue)
# 
# # 6 Top category
# category_summary[order(-TotalRevenue)][1]
# 
# # 7 Top 20 customers
# customer_summary[order(-TotalRevenue)][1:20]
# 
# # 8 Top 20 products
# product_summary[order(-TotalQuantity)][1:20]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# dir.create("Output", showWarnings = FALSE)
# 
# fwrite(customer_summary, "Output/customer_summary.csv")
# fwrite(product_summary, "Output/product_summary.csv")
# fwrite(city_summary, "Output/city_summary.csv")
# fwrite(category_summary, "Output/category_summary.csv")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # City Transactions
# png("Output/city_transactions.png")
# barplot(city_summary$Transactions, names.arg = city_summary$City, las=2)
# dev.off()
# 
# # Category Revenue
# png("Output/category_revenue.png")
# barplot(category_summary$TotalRevenue, names.arg = category_summary$Category, las=2)
# dev.off()
# 
# # Top Customers
# top_customers <- customer_summary[order(-TotalRevenue)][1:20]
# 
# png("Output/top_customers.png")
# barplot(top_customers$TotalRevenue, names.arg = top_customers$CustomerID, las=2)
# dev.off()
# 
# # Payment Distribution
# payment <- dt[, .N, by = PaymentMethod]
# 
# png("Output/payment_distribution.png")
# pie(payment$N, labels = payment$PaymentMethod)
# dev.off()

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Show City Transactions
# barplot(city_summary$Transactions, names.arg = city_summary$City, las=2)
# 
# # Show Category Revenue
# barplot(category_summary$TotalRevenue, names.arg = category_summary$Category, las=2)
# 
# # Show Top Customers
# top_customers <- customer_summary[order(-TotalRevenue)][1:20]
# barplot(top_customers$TotalRevenue, names.arg = top_customers$CustomerID, las=2)
# 
# # Show Payment Distribution
# payment <- dt[, .N, by = PaymentMethod]
# pie(payment$N, labels = payment$PaymentMethod)

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open('Output/city_transactions.png')
plt.imshow(img)
plt.axis('off')